data:
  split_date: '2010-01-01'
  test_size: 0.2
  random_state: 42
  
models:
  random_forest:
    n_estimators: 200
    max_depth: 15
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    
  lstm:
    sequence_length: 12
    lstm_units: 50
    dropout: 0.2
    epochs: 50
    batch_size: 32
    learning_rate: 0.001
    
  arima:
    order: [2, 1, 2]
    seasonal_order: [1, 1, 1, 12]

training:
  validation_split: 0.2
  early_stopping_patience: 10
  metrics_to_track:
    - rmse
    - mae
    - r2
    - mape
